### ISSUE TITLE
Tarjetas SIM

### ISSUE THREAD

**Issue by Jorjo80** [dsrosado/NB-IoT#2]
Buenas,

Soy Jorge Contreras, un estudiante de la UPM, y estoy desarrollando mi TFM con NB-IoT.
Estoy intentando contactar con Vodafone y Telefónica para conseguir las tarjetas SIM con este servicio, pero sin éxito. ¿Cómo pudiste tu solicitar la información?

Mi correo es j.cortiz@alumnos.upm.es

Muchas gracias de antemano

Un saludo.

**Comment by dsrosado** [comment]
Hola Jorge. 
Intenta contactar con sus comerciales para servicios profesionales a empresas.
